# ======== Base Image: Python 3.10+ required for SentenceTransformer & Qdrant ========
FROM python:3.10-slim

# ======== System dependencies ========
RUN apt-get update && \
    apt-get install -y --no-install-recommends \
        build-essential \
        gcc \
        git \
        curl \
    && rm -rf /var/lib/apt/lists/*

# ======== Set workdir ========
WORKDIR /app

# ======== Copy requirements ========
COPY requirements.txt .

# ======== Install python dependencies ========
RUN pip install --upgrade pip && \
    pip install --no-cache-dir -r requirements.txt

# ======== Copy app source code ========
COPY . .

# ======== Expose Flask port ========
EXPOSE 5000

# ======== Environment variables for Flask ========
ENV FLASK_APP=app
ENV FLASK_RUN_HOST=0.0.0.0
ENV FLASK_RUN_PORT=5000

# ======== Optional: for Stable startup log ========
ENV PYTHONUNBUFFERED=1

# ======== Start the application ========
CMD ["flask", "run"]
